### ISSUE TITLE
Webhook 404

### ISSUE THREAD

**Issue by icbestCA** [lukassoo/mdBookGitAutoBuild#1]
Hi, I really like your app and i want to use it for my personal wiki, but i have an issue with the webhook.
I use GitLab for the git repo and they have the webhook function, but it seem that it doesnt update MDbook.
I use the docker version, here my command: 
`docker run -d --name mdBookGitAutoBuilder -e GIT_REPO_LINK=git@gitlab.com:[redacted]/docs.git -e USE_WEB_HOOK='1' -p 5055:80 -p 5555:8080 --restart unless-stopped lukassoo/mdbook-git-auto-build:latest`
It works correctly with the interval time, but i wanted something faster. Here what I get as a respond from the webhook URL (I host it on my computer for now and uses my domain for access): 
![Capture d’écran 2024-11-23 104200](https://github.com/user-attachments/assets/cd74f386-6143-4987-b4fc-04d2230bc614)

Here are my docker logs and env variable: 
```
Starting
Scanning repo ssh keys and adding to trusted
Cloning...
Cloning completed
Last commit time: 1732373153

Building mdBook
Staring http server (port 80)
Detected USE_WEB_HOOK - starting http web hook listener

C:\Users\[user]>docker exec mdBookGitAutoBuilder env

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=01e893301768
GIT_REPO_LINK=git@gitlab.com:[redacted]/docs.git
USE_WEB_HOOK='1'
ASPNETCORE_URLS=http://+:80
DOTNET_RUNNING_IN_CONTAINER=true
DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true
DOTNET_VERSION=7.0.5
HOME=/root
```
Here is GitLab page: 
![image](https://github.com/user-attachments/assets/a5b926cc-a31b-4a48-8a42-eb501fb04ef7)

Thanks, tell me if you need other infos.

**Comment by lukassoo** [comment]
If I understand correctly you are trying to reach the listener on the IP:Port address.
If i recall correctly and from what I typed in the Readme - you should go to "/home".

Try "localhost:5555/hook" and let me know if it works 🙂

**Comment by icbestCA** [comment]
Indeed, the /hook is working perfectly for the webhook! Thank you. Upon reviewing the documentation again, I noticed it isn’t mentioned in the README. It would be great to have it added for clarity. Thanks again!

**Comment by lukassoo** [comment]
_USE_WEB_HOOK='1' - Activates the web hook request listener on port 8080 that listens on the path **"/hook"** (that is inside the container, you can adjust the bindings outside)_

I'll probably move the documentation to wiki pages to make it more clear 👍
